### ISSUE TITLE
Feature 1: User can choose between viewing a list anime or manga

### ISSUE THREAD

**Issue by Blake-Frangoulis** [Blake-Frangoulis/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can choose between a list of Top 50 Anime or Top 50 Manga of all time sorted by their MyAnimeList user rating.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to view a navbar and select between "Anime" or "Manga" and choose which list they would like to view. With the default view being the top 50 rated Anime

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop View
![Desktop View](https://github.com/Blake-Frangoulis/ajax-project/assets/130610365/87e0922c-71e8-40ca-9548-7673b8bf6c7a)
Mobile View
![Mobile View](https://github.com/Blake-Frangoulis/ajax-project/assets/130610365/527db0fa-4352-4421-b478-448eb97cf77d)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML required for the navbar in a "header-container" using responsive layout classes for the elements inside.
    - [x] Create anchor elements for "Anime" and "Manga" to match figma example.
- [x]  Create two functions getTopAnime and getTopManga that do that following
   - [x] Creates a new XMLHttpRequest
   - [x] Performs a 'Get' request to the API to retrieve the top anime or manga respectively by their user rating on myanimelist.
   - [x] Returns a response type of 'JSON'
   - [x] Sends the XHR request
   - [x] Creates an array named "topAnime" or "topManga" respectively
   - [x] Adds an event listener to the XHR request to on 'load' store the first 50 objects returned by the request to the arrays topAnime and topManga respectively.
- [x] Create a container HTML element in the main element
- [x] Inside that container create a div element with the class "list-container"
- [x] Inside list-container create two divs for "top-anime-header" and "top-manga-header" that will display above each list to clearly show which list is being displayed
- [x] Inside the list-container create two divs. One with the class "anime-list" and one with the class "manga-list" each containing "data-view" attributes to specify them for viewSwap function.
- [x] Create dummy anime and manga cards in each list div. Containing the image, title, and rating #. 
- [x] Stylize with a background of a different shade than background of the page and for responsivity
- [x] Create two functions renderTopAnime and renderTopManga with one parameter (card) that represents one object from the topAnime or topManga arrays that does the following
    - [x] Renders a DOM tree for the title formatted to match the example HTML entries.
    - [x] Appends DOM tree to the appropriate container.
- [x] Remove example html entries from containers
- [x] Create a div with the class "loading-screen" as a sibling to the main element. In this div add a loading gif to display while the content is loading
- [x] Add event listener to the document for the DOMContentLoaded event that will utilize a setTimeout to
     - [x] Create both topAnime and topManga lists after a delay
     - [x] Swap the view to the Top Anime List
- [x]  In the createTopAnime function, because it will be loaded and displayed first, add a line to add the hidden class to the loading-screen modal
- [x] Create function viewSwap with a single parameter representing the name of the view to show.
- [x] Add event listeners to "Anime" and "Manga" anchor elements on the navbar  to swap the view to the desired container.

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
